CREATE TABLE CAR (
    CAR_NUMBER VARCHAR2(20) PRIMARY KEY,
    TYPE VARCHAR2(20)
);

CREATE TABLE PARKED_CARS (
    CAR_NUMBER VARCHAR2(20) PRIMARY KEY,
    PARKING_TIME TIMESTAMP,
    FOREIGN KEY (CAR_NUMBER) REFERENCES CAR(CAR_NUMBER)
);

-- 입차 감지 트리거
CREATE OR REPLACE TRIGGER car_entry_trigger
AFTER INSERT ON PARKED_CARS
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Car ' || :NEW.CAR_NUMBER || ' entered the parking lot at ' || :NEW.PARKING_TIME);
END;
/

-- 출차 감지 트리거
CREATE OR REPLACE TRIGGER car_exit_trigger
AFTER DELETE ON PARKED_CARS
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Car ' || :OLD.CAR_NUMBER || ' exited the parking lot.');
END;
/